services:
  picar_humble_raspi:
    image: ghcr.io/rwu-r2m/ros_raspi:arm64  # Use arm64 tag for Raspberry Pi 5
    environment:
        ROS_DOMAIN_ID: 1
        DISPLAY: $DISPLAY
    network_mode: host
    stdin_open: true
    privileged: true
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - $HOME/.Xauthority:/root/.Xauthority
        - /dev:/dev  # Give access to hardware devices
    devices:
        - /dev/gpiomem:/dev/gpiomem  # GPIO access
        - /dev/i2c-1:/dev/i2c-1      # I2C access
        - /dev/can0:/dev/can0        # CAN bus access
    command: /bin/bash -c "exec bash"