services:
  humble_raspi:
    image: ghcr.io/rwu-r2m/ros_raspi:arm64
    platform: linux/arm64/v8
    environment:
        ROS_DOMAIN_ID: 1
        DISPLAY: $DISPLAY
    network_mode: host
    stdin_open: true
    privileged: true
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - $HOME/.Xauthority:/root/.Xauthority
        - /dev:/dev
        - ../src:/root/ros2_ws/src  # Single source mount
    devices:
        - /dev/gpiomem:/dev/gpiomem
        - /dev/i2c-1:/dev/i2c-1
        - /dev/can0:/dev/can0
    command: >
      /bin/bash -c "
        source /opt/ros/humble/setup.bash &&
        exec bash"